/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AttachmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mime', 'name', 'path', 'size', 'userId'] as const
  $columns = AttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mime: string
  @column()
  declare name: string
  @column()
  declare path: string
  @column()
  declare size: number
  @column()
  declare userId: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DocumentSchema extends BaseModel {
  static $columns = [
    'active',
    'category',
    'content',
    'createdAt',
    'document',
    'id',
    'name',
    'picture',
    'updatedAt',
    'userId',
  ] as const
  $columns = DocumentSchema.$columns
  @column()
  declare active: boolean | null
  @column()
  declare category: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare document: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare picture: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class EnrollmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'unitId', 'updatedAt', 'userId'] as const
  $columns = EnrollmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare unitId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class LogSchema extends BaseModel {
  static $columns = ['createdAt', 'endpoint', 'id', 'method', 'payload', 'userId'] as const
  $columns = LogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare endpoint: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare method: string
  @column()
  declare payload: string | null
  @column()
  declare userId: number
}

export class MinuteSchema extends BaseModel {
  static $columns = [
    'active',
    'content',
    'createdAt',
    'description',
    'document',
    'id',
    'name',
    'updatedAt',
    'userId',
  ] as const
  $columns = MinuteSchema.$columns
  @column()
  declare active: boolean | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare document: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ParkingRequestSchema extends BaseModel {
  static $columns = [
    'authorization',
    'createdAt',
    'id',
    'insurancePolicy',
    'notes',
    'period',
    'periodYear',
    'status',
    'technicalReview',
    'unitId',
    'updatedAt',
    'userId',
    'vehicleId',
  ] as const
  $columns = ParkingRequestSchema.$columns
  @column()
  declare authorization: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare insurancePolicy: string | null
  @column()
  declare notes: string | null
  @column()
  declare period: string
  @column()
  declare periodYear: number
  @column()
  declare status: string
  @column()
  declare technicalReview: string | null
  @column()
  declare unitId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare vehicleId: number | null
}

export class UnitSchema extends BaseModel {
  static $columns = [
    'apto',
    'buildArea',
    'coefficient',
    'createdAt',
    'debt',
    'floor',
    'id',
    'name',
    'notes',
    'privateArea',
    'status',
    'tower',
    'typology',
    'updatedAt',
  ] as const
  $columns = UnitSchema.$columns
  @column()
  declare apto: number
  @column()
  declare buildArea: string | null
  @column()
  declare coefficient: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare debt: number
  @column()
  declare floor: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare privateArea: string | null
  @column()
  declare status: string
  @column()
  declare tower: number
  @column()
  declare typology: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'document',
    'documentType',
    'email',
    'fullName',
    'id',
    'password',
    'phone',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string | null
  @column()
  declare documentType: string
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleSchema extends BaseModel {
  static $columns = [
    'brand',
    'color',
    'createdAt',
    'driverLicense',
    'id',
    'isOwner',
    'model',
    'ownerCard',
    'ownerDocument',
    'ownerName',
    'plate',
    'userId',
    'vehicleType',
    'year',
  ] as const
  $columns = VehicleSchema.$columns
  @column()
  declare brand: string | null
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare driverLicense: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isOwner: boolean | null
  @column()
  declare model: string | null
  @column()
  declare ownerCard: string
  @column()
  declare ownerDocument: string
  @column()
  declare ownerName: string
  @column()
  declare plate: string | null
  @column()
  declare userId: number
  @column()
  declare vehicleType: string
  @column()
  declare year: number
}
