/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Enrollments: () => import('#controllers/admin/enrollments_controller'),
    Imports: () => import('#controllers/admin/imports_controller'),
    Logs: () => import('#controllers/admin/logs_controller'),
    Units: () => import('#controllers/admin/units_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  Auth: () => import('#controllers/auth_controller'),
  board: {
    Documents: () => import('#controllers/board/documents_controller'),
    ParkingRequests: () => import('#controllers/board/parking_requests_controller'),
  },
  Profile: () => import('#controllers/profile_controller'),
  security: {
    Units: () => import('#controllers/security/units_controller'),
    Visitors: () => import('#controllers/security/visitors_controller'),
  },
  user: {
    Attachments: () => import('#controllers/user/attachments_controller'),
    Authorizations: () => import('#controllers/user/authorizations_controller'),
    Documents: () => import('#controllers/user/documents_controller'),
    Enrollments: () => import('#controllers/user/enrollments_controller'),
    Vehicles: () => import('#controllers/user/vehicles_controller'),
    Visitors: () => import('#controllers/user/visitors_controller'),
  },
}
